trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: AzurePowerShell@5
  inputs:
    inputs:
    azureSubscription: 'new'
    ScriptType: 'InlineScript'
    Inline: |
      $context = Get-AzContext
      $appId = $context.Account.Id
      $tenantId = $context.Tenant.Id

      # If you need to fetch credentials for an app registration
      # Replace the following placeholders with actual logic
      $appSecret = 'ProvideAppSecretHere'

      $appIdEncoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($appId))
      Write-Host "App registration Id:"
      Write-Output $appIdEncoded

      $appSecretEncoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($appSecret))
      Write-Host "App registration secret:"
      Write-Output $appSecretEncoded

      $tenantIdEncoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($tenantId))
      Write-Host "Tenant Id:"
      Write-Output $tenantIdEncoded
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
